### PR TITLE
fix: remove unused React imports

### PR DESCRIPTION
**Pull request by DanielRuf**
### Please check if the PR fulfills these requirements ###

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
This PR removes unused React imports.

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)**

**Other information:**

### CODE REVIEW

**Comment by DanielRuf** [comment]
I know, I was not finished yet =) It was abit late when I started this PR. I will finish it today.

**Comment by tutok** [comment]
I think it will be reasonable to add  `'@typescript-eslint/no-unused-vars': 'error',` rule for `TS` overrides, tested it quickly - it works in VSC, but `lint` script is not, so probably some dependency update is needed?

**Comment by DanielRuf** [comment]
For me the following works:

```json
{
  "extends": ["@deity/eslint-config-falcon"],
  "rules": {
    "@typescript-eslint/no-unused-vars": "error"
  }
}
```

```
"lint": "eslint ./packages/falcon-ui-kit"
```

It seems like the files in the pckacges are not read by default.

```shell
yarn lint
yarn run v1.19.0
$ eslint ./packages/falcon-ui-kit/**/*.tsx

/Users/danielruf/projects/falcon/packages/falcon-ui-kit/src/Filters/FilterItemListLayout.tsx
  1:8  error  'React' is defined but never used  @typescript-eslint/no-unused-vars

/Users/danielruf/projects/falcon/packages/falcon-ui-kit/src/Forms/CheckboxFormField.tsx
  26:17  error  'validate' is assigned a value but never used  @typescript-eslint/no-unused-vars
  26:27  error  'required' is assigned a value but never used  @typescript-eslint/no-unused-vars
  26:37  error  'children' is assigned a value but never used  @typescript-eslint/no-unused-vars

/Users/danielruf/projects/falcon/packages/falcon-ui-kit/src/Forms/FormField.tsx
  33:17  error  'validate' is assigned a value but never used  @typescript-eslint/no-unused-vars
  33:27  error  'required' is assigned a value but never used  @typescript-eslint/no-unused-vars

/Users/danielruf/projects/falcon/packages/falcon-ui-kit/src/Forms/RadioFormField.tsx
  25:24  error  'validate' is assigned a value but never used  @typescript-eslint/no-unused-vars
  25:34  error  'required' is assigned a value but never used  @typescript-eslint/no-unused-vars

/Users/danielruf/projects/falcon/packages/falcon-ui-kit/src/Price/Price.tsx
  13:33  error  'children' is assigned a value but never used  @typescript-eslint/no-unused-vars

/Users/danielruf/projects/falcon/packages/falcon-ui-kit/src/SortOrder/SortOrderPickerLayout.tsx
  1:8  error  'React' is defined but never used  @typescript-eslint/no-unused-vars

✖ 10 problems (10 errors, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```


Default setting for the `lint`script results in:
```shell
yarn lint
yarn run v1.19.0
$ eslint ./

/Users/danielruf/projects/falcon/packages/falcon-client/build-utils/webpack/config/create.js
  77:11  error  'minimize' is assigned a value but never used  @typescript-eslint/no-unused-vars

/Users/danielruf/projects/falcon/packages/falcon-wordpress-api/src/index.js
  315:13  error  'content' is defined but never used  @typescript-eslint/no-unused-vars

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by DanielRuf** [comment]
For me the following works:

```json
{
  "extends": ["@deity/eslint-config-falcon"],
  "rules": {
    "@typescript-eslint/no-unused-vars": "error"
  }
}
```

```
"lint": "eslint ./packages/falcon-ui-kit"
```

It seems like the files in the packages are not read by default because they are tsx not js.

```shell
yarn lint
yarn run v1.19.0
$ eslint ./packages/falcon-ui-kit/**/*.tsx

/Users/danielruf/projects/falcon/packages/falcon-ui-kit/src/Filters/FilterItemListLayout.tsx
  1:8  error  'React' is defined but never used  @typescript-eslint/no-unused-vars

/Users/danielruf/projects/falcon/packages/falcon-ui-kit/src/Forms/CheckboxFormField.tsx
  26:17  error  'validate' is assigned a value but never used  @typescript-eslint/no-unused-vars
  26:27  error  'required' is assigned a value but never used  @typescript-eslint/no-unused-vars
  26:37  error  'children' is assigned a value but never used  @typescript-eslint/no-unused-vars

/Users/danielruf/projects/falcon/packages/falcon-ui-kit/src/Forms/FormField.tsx
  33:17  error  'validate' is assigned a value but never used  @typescript-eslint/no-unused-vars
  33:27  error  'required' is assigned a value but never used  @typescript-eslint/no-unused-vars

/Users/danielruf/projects/falcon/packages/falcon-ui-kit/src/Forms/RadioFormField.tsx
  25:24  error  'validate' is assigned a value but never used  @typescript-eslint/no-unused-vars
  25:34  error  'required' is assigned a value but never used  @typescript-eslint/no-unused-vars

/Users/danielruf/projects/falcon/packages/falcon-ui-kit/src/Price/Price.tsx
  13:33  error  'children' is assigned a value but never used  @typescript-eslint/no-unused-vars

/Users/danielruf/projects/falcon/packages/falcon-ui-kit/src/SortOrder/SortOrderPickerLayout.tsx
  1:8  error  'React' is defined but never used  @typescript-eslint/no-unused-vars

✖ 10 problems (10 errors, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```


Default setting for the `lint`script results in:
```shell
yarn lint
yarn run v1.19.0
$ eslint ./

/Users/danielruf/projects/falcon/packages/falcon-client/build-utils/webpack/config/create.js
  77:11  error  'minimize' is assigned a value but never used  @typescript-eslint/no-unused-vars

/Users/danielruf/projects/falcon/packages/falcon-wordpress-api/src/index.js
  315:13  error  'content' is defined but never used  @typescript-eslint/no-unused-vars

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by nimobeeren** [comment]
I can confirm, `yarn lint` only lints `.js` files, not `.ts` or `.tsx`. The recommended way to include other extensions is ESLint's [`--ext` option](https://eslint.org/docs/user-guide/command-line-interface#--ext).

I will create a PR that fixes this for our npm scripts.

**Comment by DanielRuf** [comment]
Ah that makes sense, thanks for the hint. I've never really used `--ext` as most setups were preconfigured or we directly used tslint and the strict mode.

**Pull request merged**
