### PR TITLE
Updating versions for internal dependencies + deduplicating

### LINKED ISSUE #561: deduplicate dependencies in yarn.lock
**What should be changed/improved?**
`yarn.lock` contains tons of duplicated packages, we could optimize it.

**Your suggested solution**
probably we can automate it via [yarn-deduplicate](https://www.npmjs.com/package/yarn-deduplicate#deduplication-strategies) (run always on `yarn prepare`)

### PR DESCRIPTION
**Pull request by Borales**
- Updated main dependencies, like  `apollo-*` and `koa`
- Removing duplicates for `@babel` and `@emotion` (and other smaller dependencies)
- Removed duplicates from `yarn.lock`, size of `node_modules` folder:
  - Before: 640mb
  - After: 495mb (**-145mb** ⬇️🚀)
- `falcon-ui` bundle size:
  - Before: 61.64kb
  - After: back to **60.17kb** (**-1.5kb** 🎉)
- example client-app bundle:
  - Before: `Precaching 34 files, in total 1.350 MB.`
  - After: `Precaching 34 files, in total 1.336 MB.` (**-14kb** ⬇️)

Fixes #561

### CODE REVIEW

**Comment by Borales** [comment]
Cleaned up more duplicates

**Comment by nimobeeren** [comment]
Why was this `yarn.lock` removed?

**Comment by Borales** [comment]
@nimobeeren 
Screenshot 2019-10-28 at 10 24 09

it wasn't, open the diff block

**Comment by nimobeeren** [comment]
Ah, I missed that

**Pull request merged**
