### PR TITLE
fix: account icon in the header is in sync with logging in and out

### PR DESCRIPTION
**Pull request by akbarik**
### Please check if the PR fulfills these requirements ###

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
This is a bug fix for issue 446 (https://github.com/deity-io/falcon/issues/446)

**What is the current behavior? (You can also link to an open issue here)**
Logout click does not change Account icon in the header. It stays as "Account", instead of "Sign in".

**What is the new behavior (if this is a feature change)?**
Logout click changes Account icon from "Account" to "Sign in". It works both for Logout link in Banner and in Account page.

**Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)**
No

**Other information:**
-

### CODE REVIEW

**Comment by cane-lagerwaard** [comment]
@akbarik Thanks alot! We'll take a look at it asap

**Comment by akbarik** [comment]
@Borales, please let me know if there are any question regarding this PR.

**Comment by Borales** [comment]
@akbarik sure, let me check that locally

**Comment by Borales** [comment]
@akbarik Hi
I just tested this PR locally, it works. So as demo.deity.io. 

Is it possible for you to send a short video (gif) of reproducing this issue in your browser? Thanks.

DemoLogin

**Comment by akbarik** [comment]
@Borales, sure here's the GIF:
account_bug

**Comment by Borales** [comment]
@akbarik I think I got it on my local

**Comment by Borales** [comment]
but it's not on demo (it's latest release) - this is weird :)

**Comment by cane-lagerwaard** [comment]
@Borales it's also happening here https://latest.snapshot.deity.io/

**Comment by nimobeeren** [comment]
I have it on local as well, your fix seems to work.

@akbarik what is the reasoning behind your change? I noticed that when the structure is `CustomerQuery > OpenSideBarMutation`, the icon is updated, while with `OpenSidebarMutation > Fragment > CustomerQuery` it is not.

It also seemed to be working correctly without the change to `SignOutLogic`, is there any particular reason you made those changes?

**Comment by akbarik** [comment]
It's a difficult question, @nimobeeren :) I can't exactly remember why this specific change fixes the issue, but it works, right? If you can find a better solution, please provide it.

**Pull request merged**
