### PR TITLE
Node source-maps support

### PR DESCRIPTION
**Pull request by Borales**

### CODE REVIEW

**Comment by mateuszwozniak** [comment]
What about Falcon Client?

**Comment by Borales** [comment]
@mateuszwozniak I didn't want to mix all the source-maps at once, it was a part of another task, but ok, added

**Comment by tutok** [comment]
@mateuszwozniak do you mean adding 
```
require('source-map-support').install();
```
also here https://github.com/deity-io/falcon/blob/8e1030088f4477d39b7e9ab325d367499c69cc9a/packages/falcon-client/src/index.js#L1
❔

**Comment by mateuszwozniak** [comment]
@tutok yes

**Comment by Borales** [comment]
@mateuszwozniak added

**Pull request merged**
